name: Continuous Integration

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          components: clippy, rustfmt

      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Check build
        working-directory: oracle-ingestor-lambda
        run: cargo build

      - name: Check formatting
        working-directory: oracle-ingestor-lambda
        run: cargo fmt -- --check

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path oracle-ingestor-lambda/Cargo.toml -- -Dclippy::all
